Devoiture/Models/Momo/MomoCreatePaymentResponseModel.cs
namespace Devoiture.Models.Momo
{
    public class MomoCreatePaymentResponseModel
    {
        public string RequestId { get; set; }
        public int ErrorCode { get; set; }
        public string OrderId { get; set; }
        public string Message { get; set; }
        public string LocalMessage { get; set; }
        public string RequestType { get; set; }
        public string PayUrl { get; set; }
        public string Signature { get; set; }
        public string QrCodeUrl { get; set; }
        public string Deeplink { get; set; }
        public string DeeplinkWebInApp { get; set; }
    }
}

Devoiture/Models/Momo/MomoExecuteResponseModel.cs
namespace Devoiture.Models.Momo
{
    public class MomoExecuteResponseModel
    {
        public string OrderId { get; set; } 
        public string OrderInfo { get; set; }
        public int Amount { get; set; }
        public string FullName { get; set; }
        public int Mayc {  get; set; }
    }
}

Devoiture/Models/Momo/MomoOptionModel.cs
namespace Devoiture.Models.Momo
{
    public class MomoOptionModel
    {
        public string MomoApiUrl { get; set; }
        public string SecretKey { get; set; }
        public string AccessKey { get; set; }
        public string ReturnUrl { get; set; }
        public string NotifyUrl { get; set; }
        public string PartnerCode { get; set; }
        public string RequestType { get; set; }
    }
}

Devoiture/Controllers/MomoController.cs
using Devoiture.Helpers;
using Devoiture.Models;
using Devoiture.Models.Momo;
using Devoiture.Models.Order;
using Devoiture.Service;
using Devoiture.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Devoiture.Controllers
{
    public class MomoController : Controller
    {
        private readonly IMomoService _momoService;
        private readonly Devoiture1Context _context;

        public MomoController(IMomoService momoService, Devoiture1Context context)
        {
            _momoService = momoService;
            _context = context;
        }
        public IActionResult CreatePaymentUrl(int mayc)
        {
            var chitietyc = (from yc in _context.Yeucauthuexes
                             join xe in _context.Xes on yc.Biensoxe equals xe.Biensoxe
                             join chuxe in _context.Taikhoans on yc.Nguoithue equals chuxe.Email
                             where yc.MaYc == mayc
                             select new ChitietycThanhtoan_VM
                             {
                                 MaYc = yc.MaYc,
                                 TenMauXe = xe.MaMxNavigation.TenMx,
                                 Chuxe = chuxe.Email,
                                 BienSoXe = yc.Biensoxe,
                                 TongTienThue = yc.Tongtienthue,
                                 HoTen = chuxe.HoTen,
                                 Sdt = chuxe.Sdt,
                                 Baohiemthuexe = yc.Baohiemthuexe
                             }).FirstOrDefault();

            if (chitietyc == null)
            {
                return NotFound();
            }

            var momo = new MomoExecuteResponseModel
            {
                FullName = chitietyc.HoTen,
                Mayc = mayc,
                OrderInfo = $"{chitietyc.HoTen} thanh toán tiền cọc cho xe {chitietyc.BienSoXe}",
                Amount = (int)(chitietyc.TongTienThue * 0.3)
            };
            return View("CreatePaymentUrl", momo);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePaymentUrl(OrderInfoModel model)
        {
            var response = await _momoService.CreatePaymentAsync(model);
            return Redirect(response.PayUrl);
        }
        [HttpGet]
        public IActionResult PaymentCallBack()
        {
            var response = _momoService.PaymentExecuteAsync(HttpContext.Request.Query);
            var orderInfo = _context.Yeucauthuexes.FirstOrDefault(yc => yc.MaYc == response.Mayc);
            if (orderInfo != null)
            {
                var khachhang = _context.Taikhoans.FirstOrDefault(t => t.Email == orderInfo.Nguoithue);
                var chuxe = _context.Taikhoans.FirstOrDefault(t => t.Email == orderInfo.Chuxe);
                if (khachhang != null)
                {
                    var hoadonThuexe = new HoadonThuexe
                    {
                        MaHd = response.OrderId,
                        MaYc = orderInfo.MaYc,
                        Email = orderInfo.Nguoithue,
                        Biensoxe = orderInfo.Biensoxe,
                        NgaylapHd = DateTime.Now,
                        HoTen = response.FullName,
                        Sdt = khachhang.Sdt,
                        Tiendatcoc = Math.Round(orderInfo.Tongtienthue * 0.3, 0),
                        Baohiemthuexe = Math.Round(orderInfo.Baohiemthuexe, 0),
                        TongTienThue = Math.Round(orderInfo.Tongtienthue, 0),
                        Sotiencantra = Math.Round(orderInfo.Tongtienthue, 0) - response.Amount,
                    };
                    var hoadonchothuexe = new HoaDonChoThueXe
                    {
                        MaHdct = response.OrderId,
                        MaYc = orderInfo.MaYc,
                        Email = orderInfo.Chuxe,
                        Biensx = orderInfo.Biensoxe,
                        NglapHd = DateTime.Now,
                        Hoten = chuxe.HoTen,
                        Sdt = khachhang.Sdt,
                        Tongtiennhanduoc = response.Amount
                    };
                    _context.HoadonThuexes.Add(hoadonThuexe);
                    _context.HoaDonChoThueXes.Add(hoadonchothuexe);
                    orderInfo.Matt = 4;
                    orderInfo.Sotiencantra = Math.Round(orderInfo.Tongtienthue, 0) - response.Amount;
                    _context.Yeucauthuexes.Update(orderInfo);
                    _context.SaveChanges();
                    TempData["success"] = "Đã thanh toán tiền cọc thành công. Quý khách vui lòng thanh toán số tiền còn lại với chủ xe";
                }
            }
            return RedirectToAction("Index", "Home");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Devoiture/Views/Momo/CreatePaymentUrl.cshtml
@model Devoiture.Models.Momo.MomoExecuteResponseModel

@{
    ViewData["Title"] = "Xác nhận thanh toán";
    var postUrl = "tich-hop-thanh-toan-momo-voi-asp-net-core-7d5e4hP";
}

<div class="container py-5">
    <h1 class="display-4 text-uppercase text-center mb-5">Xác nhận thanh toán</h1>
    <div class="row justify-content-center">
        <div class="col-lg-8 mb-2">
            <div class="contact-form bg-white mb-4 shadow p-4 rounded">
                <form asp-action="CreatePaymentUrl" asp-controller="Momo" method="post">
                    <div class="form-group">
                        <label for="fullName" class="font-weight-bold">Họ và tên:</label>
                        <input type="text" id="fullName" class="form-control p-4" value="@Model.FullName" readonly />
                    </div>
                    <div class="form-group">
                        <label for="amount" class="font-weight-bold">Số tiền cọc cần thanh toán:</label>
                        <input type="text" id="amount" class="form-control p-4" value="@Model.Amount" readonly />
                    </div>
                    <div class="form-group">
                        <label for="orderInfo" class="font-weight-bold">Nội dung thanh toán:</label>
                        <input type="text" id="orderInfo" class="form-control p-4" value="@Model.OrderInfo" readonly />
                    </div>
                    <input type="hidden" asp-for="OrderId" />
                    <input type="hidden" asp-for="Mayc"/>
                    <input type="hidden" asp-for="OrderInfo" />
                    <input type="hidden" asp-for="Amount" />
                    <input type="hidden" asp-for="FullName" />
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary py-3 px-5">Xác nhận thanh toán</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Devoiture/Views/Momo/PaymentCallBack.cshtml
@model Devoiture.Models.Momo.MomoExecuteResponseModel

@{
    ViewData["Title"] = "Home Page";
    var postUrl = "tich-hop-thanh-toan-momo-voi-asp-net-core-7d5e4hP";
}

<div class="text-center">
    <div class="container">
        <h1 class="text-success">Thanh Toán Thành Công</h1>
        <p>Order ID: <strong>@Model.OrderId</strong></p>
        <p>Amount: <strong>@Model.Amount</strong></p>
        <p>Order Info: <strong>@Model.OrderInfo</strong></p>
    </div>
</div>