Devoiture/Controllers/XeKHController.cs
using Devoiture.Models;
using Devoiture.ViewModel;
using Devoiture.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AutoMapper;

namespace Devoiture.Controllers
{
    [Authorize]
    public class XeKHController : Controller
    {
        private readonly Devoiture1Context _context;
        private readonly IMapper _imapper;

        public XeKHController(Devoiture1Context context, IMapper mapper)
        {
            _context = context;
            _imapper = mapper;
        }
        public IActionResult DanhsachxecuaKH()
        {
            var kh = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySettings.ACCOUNT_KEY).Value;
            var dsxe = _context.Xes
            .Where(xm => xm.Email == kh)
            .Select(x => new DanhsachxeKH_VM
            {
                Biensoxe = x.Biensoxe,
                TenXe = x.MaMxNavigation.TenMx,
                NamSx = x.NamSx,
                Tenloai = x.MaLoaiNavigation.TenLoai,
                Muctieuthunhienlieu = x.Muctieuthunhienlieu,
                Hinhanh = x.Hinhanh,
                Trangthaibaotri = x.Trangthaibaotri,
                TrangthaiDuyet = x.TrangthaiDuyet,
                Hide = x.Hide
            })
            .OrderBy(p => p.TenXe)
            .ToList();
            return View(dsxe);
        }
        [HttpGet]
        public IActionResult ThemXe()
        {
            var viewModel = new ThemxeVM();
            LoadDropdownLists(viewModel);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ThemXe(ThemxeVM model, IFormFile Hinh, List<IFormFile> HinhAnhXe)
        {
            if (ModelState.IsValid)
            {
                var kh = HttpContext.User.Claims.SingleOrDefault(p => p.Type == MySettings.ACCOUNT_KEY)?.Value;
                var xe = _imapper.Map<Xe>(model);
                xe.Email = kh;
                xe.Hide = false;
                xe.TrangthaiDuyet = false;
                xe.Trangthaibaotri = false;
                if (Hinh != null)
                {
                    xe.Hinhanh = MyUtil.UploadHinh("Xe", Hinh);
                }
                _context.Xes.Add(xe);
                _context.SaveChanges();
                foreach (var hinhAnh in HinhAnhXe)
                {
                    var hinhAnhXe = new HinhAnhXe
                    {
                        Hinh = MyUtil.UploadHinh("Xe", hinhAnh),
                        Biensoxe = xe.Biensoxe
                    };
                    _context.HinhAnhXes.Add(hinhAnhXe);
                }
                _context.SaveChanges();
                TempData["success"] = "Đăng ký cho thuê xe thành công. Vui lòng chờ xác nhận kiểm duyệt xe";
                return RedirectToAction("Index", "Home");
            }
            TempData["error"] = "Đăng ký cho thuê xe thất bại";
            LoadDropdownLists(model);
            return View(model);
        }
        private void LoadDropdownLists(ThemxeVM model)
        {
            model.LoaiXeList = _context.LoaiXes
                                        .Select(x => new SelectListItem
                                        {
                                            Value = x.MaLoai.ToString(),
                                            Text = x.TenLoai
                                        })
                                        .ToList();
            model.HangXeList = _context.HangXes
                                        .Select(x => new SelectListItem
                                        {
                                            Value = x.MaHx.ToString(),
                                            Text = x.TenHx
                                        })
                                        .ToList();
            model.KhuVucList = _context.Khuvucs
                                        .Select(x => new SelectListItem
                                        {
                                            Value = x.MaKv.ToString(),
                                            Text = x.TenKv
                                        })
                                        .ToList();
            model.MauXeList = new List<SelectListItem>();
        }
        [HttpGet]
        public IActionResult GetMauXeList(int maHx)
        {
            var mauXeList = _context.MauXes
                                    .Where(x => x.MaHx == maHx)
                                    .Select(x => new SelectListItem
                                    {
                                        Value = x.MaMx.ToString(),
                                        Text = x.TenMx
                                    })
                                    .ToList();
            return Json(mauXeList);
        }
        [HttpGet]
        public IActionResult SuaXe(string biensx)
        {
            var suaxe = _context.Xes
                    .Include(x => x.HinhAnhXes) // Include related images
                    .FirstOrDefault(p => p.Biensoxe == biensx);
            if (suaxe == null)
            {
                return NotFound(); // Handle the case where the car is not found
            }
            var model = new SuaxecuaKH_VM
            {
                Biensoxe = suaxe.Biensoxe,
                MaMx = suaxe.MaMx,
                MaLoai = suaxe.MaLoai,
                Giathue = suaxe.Giathue,
                NamSx = suaxe.NamSx,
                Soghe = suaxe.Soghe,
                Muctieuthunhienlieu = suaxe.Muctieuthunhienlieu,
                Diachixe = suaxe.Diachixe,
                Dieukhoanthuexe = suaxe.Dieukhoanthuexe,
                MotaDacDiemChucNang = suaxe.MotaDacDiemChucNang,
                Loainhienlieu = suaxe.Loainhienlieu,
                Makv = suaxe.Makv,
                Hinhanh = suaxe.Hinhanh,
                HinhAnhXe = suaxe.HinhAnhXes.Select(h => h.Hinh).ToList() // Load images from database
            };
            LoadDropdownLists1(model); // Load dropdown lists
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SuaXe(SuaxecuaKH_VM model, IFormFile Hinh,List<IFormFile> HinhAnhMoi)
        {
            if (model == null)
            {
                var suaxe1 = _context.Xes
                            .Include(x => x.HinhAnhXes) // Include related images
                            .FirstOrDefault(p => p.Biensoxe == model.Biensoxe);
                if (suaxe1 == null)
                {
                    return NotFound(); // Handle the case where the car is not found
                }
                var viewModel = new SuaxecuaKH_VM
                {
                    Biensoxe = suaxe1.Biensoxe,
                    MaMx = suaxe1.MaMx,
                    MaLoai = suaxe1.MaLoai,
                    Giathue = suaxe1.Giathue,
                    NamSx = suaxe1.NamSx,
                    Soghe = suaxe1.Soghe,
                    Muctieuthunhienlieu = suaxe1.Muctieuthunhienlieu,
                    Diachixe = suaxe1.Diachixe,
                    Dieukhoanthuexe = suaxe1.Dieukhoanthuexe,
                    MotaDacDiemChucNang = suaxe1.MotaDacDiemChucNang,
                    Loainhienlieu = suaxe1.Loainhienlieu,
                    Makv = suaxe1.Makv,
                    Hinhanh = suaxe1.Hinhanh,
                    HinhAnhXe = suaxe1.HinhAnhXes.Select(h => h.Hinh).ToList()
                };
                LoadDropdownLists1(viewModel); // Nếu cần load dropdown lists
                TempData["error"] = "Cập nhật thông tin xe thất bại";
                return View(viewModel);
            }
            var suaxe = _context.Xes.Include(x => x.HinhAnhXes).FirstOrDefault(p => p.Biensoxe == model.Biensoxe);
            if (suaxe == null)
            {
                return NotFound(); // Xử lý trường hợp không tìm thấy xe
            }

            // Cập nhật thông tin của xe
            suaxe.MaLoai = model.MaLoai;
            suaxe.MaMx = model.MaMx;
            suaxe.Giathue = model.Giathue;
            suaxe.NamSx = model.NamSx;
            suaxe.Soghe = model.Soghe;
            suaxe.Muctieuthunhienlieu = model.Muctieuthunhienlieu;
            suaxe.Diachixe = model.Diachixe;
            suaxe.Dieukhoanthuexe = model.Dieukhoanthuexe;
            suaxe.MotaDacDiemChucNang = model.MotaDacDiemChucNang;
            suaxe.Loainhienlieu = model.Loainhienlieu;
            suaxe.Makv = model.Makv;
            if(Hinh != null)
            {
                model.Hinhanh = MyUtil.UploadHinh("Xe", Hinh);
                suaxe.Hinhanh = model.Hinhanh;
            }
            _context.Xes.Update(suaxe);
            // Xóa các hình ảnh cũ không còn được sử dụng nữa
            _context.HinhAnhXes.RemoveRange(suaxe.HinhAnhXes);

            // Lưu các hình ảnh mới vào cơ sở dữ liệu và cập nhật liên kết với xe
            foreach (var hinhAnh in HinhAnhMoi)
            {
                var hinhAnhXe = new HinhAnhXe
                {
                    Hinh = MyUtil.UploadHinh("Xe", hinhAnh),
                    Biensoxe = suaxe.Biensoxe
                };
                _context.HinhAnhXes.Add(hinhAnhXe);
            }
            _context.SaveChanges();
            TempData["success"] = "Cập nhật thông tin xe thành công";
            return RedirectToAction("DanhsachxecuaKH");
        }
        private void LoadDropdownLists1(SuaxecuaKH_VM model)
        {
            model.KhuVucList = _context.Khuvucs.Select(kv => new SelectListItem
            {
                Value = kv.MaKv.ToString(),
                Text = kv.TenKv
            }).ToList();
            model.MauXeList = _context.MauXes.Select(mx => new SelectListItem
            {
                Value = mx.MaMx.ToString(),
                Text = mx.TenMx
            }).ToList();

Devoiture/Views/XeKH/SuaXe.cshtml
@model Devoiture.ViewModel.SuaxecuaKH_VM

@{
    ViewData["Title"] = "Thông tin xe";
}
@await Html.PartialAsync("_PageHeader")
<div class="container-fluid py-5">
    <div class="container pt-5 pb-3">
        <div class="row justify-content-center">
            <div class="col-lg-8 mb-2 mx-auto">
                <div class="contact-form bg-light mb-4" style="padding: 30px;">
                    <form asp-action="SuaXe" asp-controller="XeKH" method="post" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="control-label">Biển số xe</label>
                            <input readonly asp-for="Biensoxe" class="form-control" />
                            <span asp-validation-for="Biensoxe" class="text-danger"></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label class="control-label">Mẫu xe</label>
                                <select asp-for="MaMx" class="form-control" id="MaMx" name="MaMx" asp-items="Model.MauXeList"></select>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">Loại xe</label>
                                <select asp-for="MaLoai" class="form-control" asp-items="Model.LoaiXeList"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Giá thuê xe</label>
                            <input asp-for="Giathue" class="form-control" />
                            <span asp-validation-for="Giathue" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Năm sản xuất</label>
                            <input asp-for="NamSx" class="form-control" />
                            <span asp-validation-for="NamSx" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Số ghế ngồi</label>
                            <input asp-for="Soghe" class="form-control" />
                            <span asp-validation-for="Soghe" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Mức tiêu thụ nhiên liệu</label>
                            <input asp-for="Muctieuthunhienlieu" class="form-control" />
                            <span asp-validation-for="Muctieuthunhienlieu" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Thuộc khu vực</label>
                            <select asp-for="Makv" class="form-control" asp-items="Model.KhuVucList"></select>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Địa chỉ xe</label>
                            <textarea asp-for="Diachixe" class="form-control" style="height: 100px;"></textarea>
                            <span asp-validation-for="Diachixe" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Điều khoản thuê xe</label>
                            <textarea asp-for="Dieukhoanthuexe" class="form-control" style="height: 100px;"></textarea>
                            <span asp-validation-for="Dieukhoanthuexe" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Đặc điểm chức năng của xe</label>
                            <textarea asp-for="MotaDacDiemChucNang" class="form-control" style="height: 100px;"></textarea>
                            <span asp-validation-for="MotaDacDiemChucNang" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Loại nhiên liệu</label>
                            <input asp-for="Loainhienlieu" class="form-control" />
                            <span asp-validation-for="Loainhienlieu" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Hình đại diện xe</label>
                            <input type="file" name="Hinh" id="HinhInput" class="form-control" />
                            @if (!string.IsNullOrEmpty(Model.Hinhanh))
                            {
                                <img id="previewHinhDaiDienXe" src="~/images/Xe/@Model.Hinhanh" alt="Hình ảnh xe" style="max-width:150px;max-height:150px;border-radius:7px" />
                            }
                        </div>
                        <div class="form-group">
                            <label class="control-label">Hình ảnh khác</label>
                            <input type="file" name="HinhAnhMoi" class="form-control" onchange="previewImages(this, 'previewHinhAnhXe')" multiple class="form-control-file" />
                            <div id="previewHinhAnhXe" class="mt-2" style="display: flex; flex-wrap: wrap;">
                                @foreach (var hinhAnh in Model.HinhAnhXe)
                                {
                                    <div class="preview-image" style="flex: 0 0 calc(33.33% - 10px); margin-right: 10px; margin-bottom: 10px;">
                                        <img src="~/images/Xe/@hinhAnh" alt="Hình ảnh xe" style="width: 100%; height: auto; border-radius: 7px;" />
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save changes" class="btn btn-primary" />
                        </div>
                        <div class="form-group">
                            <a asp-action="DanhsachxecuaKH" asp-controller="XeKH" class="btn btn-secondary">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const sogheInput = document.getElementById("Soghe");
            sogheInput.addEventListener("keydown", (event) => {
                const value = parseInt(sogheInput.value);
                if (!/^\d$/.test(event.key) || (value === 0 && event.key === "ArrowDown")) {
                    event.preventDefault();
                }
            });
            sogheInput.addEventListener("input", () => {
                sogheInput.value = Math.max(parseInt(sogheInput.value), 0);
            });
        });

        document.getElementById('HinhInput').addEventListener('change', function () {
            previewImage(this);
        });

        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewHinhDaiDienXe').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        function previewImages(input, previewId) {
            var previewContainer = document.getElementById(previewId);
            previewContainer.innerHTML = ''; // Xóa bỏ các hình ảnh hiện có để cập nhật mới

            if (input.files) {
                var files = input.files;
                for (var i = 0; i < files.length; i++) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = document.createElement('img');
                        img.src = e.target.result;
                        img.style.maxWidth = '200px';
                        img.style.marginTop = '10px';

                        var div = document.createElement('div'); // Tạo một div mới cho mỗi hình ảnh
                        div.appendChild(img);

                        previewContainer.appendChild(div); // Thêm div vào previewContainer
                    }
                    reader.readAsDataURL(files[i]);
                }
            }
        }
    </script>
}

Devoiture/Views/XeKH/ThemXe.cshtml
@model Devoiture.ViewModel.ThemxeVM

@{
    ViewData["Title"] = "Đăng kí cho thuê xe tự lái";
}
@await Html.PartialAsync("_PageHeader")
<div class="container-fluid py-5 bg-light">
    <div class="container pt-5 pb-3">
        <h1 class="display-4 text-uppercase text-center mb-5">Đăng ký cho thuê xe</h1>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <form asp-action="ThemXe" asp-controller="XeKH" method="post" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
                            <div class="form-group">
                                <label class="control-label">Biển số xe <span class="text-danger">(Lưu ý: Chỉ được nhập 1 lần duy nhất)</span></label>
                                <input asp-for="Biensoxe" class="form-control" placeholder="Nhập biển số xe" />
                                <span asp-validation-for="Biensoxe" class="text-danger"></span>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Hãng xe</label>
                                        <select asp-for="MaHx" class="form-control" id="MaHx">
                                            <option value="">Chọn hãng xe</option>
                                            @foreach (var item in Model.HangXeList)
                                            {
                                                <option value="@item.Value">@item.Text</option>
                                            }
                                        </select>

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label">Mẫu xe</label>
                                        <select asp-for="MaMx" class="form-control" id="MaMxSelect">
                                            <option value="">Chọn mẫu xe</option>
                                        </select>
                                        <input type="hidden" asp-for="MaMx" id="MaMxHidden" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Loại xe</label>
                                <select asp-for="MaLoai" class="form-control" id="MaLoai">
                                    <option value="">Chọn loại xe</option>
                                    @foreach (var item in Model.LoaiXeList)
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Soghe" class="control-label">Số ghế</label>
                                <input asp-for="Soghe" class="form-control" id="Soghe" placeholder="Nhập số ghế" />
                                <span asp-validation-for="Soghe" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="NamSx" class="control-label">Năm sản xuất</label>
                                <input asp-for="NamSx" class="form-control" placeholder="Nhập năm sản xuất" />
                                <span asp-validation-for="NamSx" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Loainhienlieu" class="control-label">Loại nhiên liệu</label>
                                <input asp-for="Loainhienlieu" class="form-control" placeholder="VD: Xăng" />
                                <span asp-validation-for="Loainhienlieu" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Muctieuthunhienlieu" class="control-label">Mức tiêu thụ nhiên liệu</label>
                                <input asp-for="Muctieuthunhienlieu" class="form-control" placeholder="Nhập mức tiêu thụ nhiên liệu" />
                                <span asp-validation-for="Muctieuthunhienlieu" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Giathue" class="control-label">Giá thuê</label>
                                <input asp-for="Giathue" class="form-control" placeholder="Nhập giá thuê" />
                                <span asp-validation-for="Giathue" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Khu vực</label>
                                <select asp-for="Makv" class="form-control" id="Makv">
                                    <option value="">Thuộc khu vực</option>
                                    @foreach (var item in Model.KhuVucList)
                                    {
                                        <option value="@item.Value">@item.Text</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Diachixe" class="control-label">Địa chỉ cho thuê xe</label>
                                <textarea asp-for="Diachixe" class="form-control" rows="3" placeholder="Nhập địa chỉ" required></textarea>
                                <span asp-validation-for="Diachixe" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Dieukhoanthuexe" class="control-label">Điều khoản thuê xe</label>
                                <textarea asp-for="Dieukhoanthuexe" class="form-control" rows="3" placeholder="Nhập điều khoản thuê xe" required></textarea>
                                <span asp-validation-for="Dieukhoanthuexe" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MotaDacDiemChucNang" class="control-label">Đặc điểm chức năng của xe</label>
                                <textarea asp-for="MotaDacDiemChucNang" class="form-control" rows="3" placeholder="Nhập đặc điểm chức năng của xe" required></textarea>
                                <span asp-validation-for="MotaDacDiemChucNang" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Hình đại diện của xe</label>
                                <input type="file" name="Hinh" id="HinhInput" class="form-control-file" />
                                <img id="previewHinhDaiDienXe" src="#" alt="Ảnh trước" style="max-width: 200px; margin-top: 10px;" />
                                <span class="text-danger">@ViewData["HinhErrorMessage"]</span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Hình ảnh khác (nếu có)</label>
                                <input type="file" name="HinhAnhXe" onchange="previewImages(this, 'previewHinhAnhXe')" multiple class="form-control-file" />
                                <div id="previewHinhAnhXe" class="mt-2"></div>
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="btn btn-primary">Cho thuê xe</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const maHxSelect = document.getElementById("MaHx");
            const maMxSelect = document.getElementById("MaMxSelect");
            const maMxHidden = document.getElementById("MaMxHidden");

            maHxSelect.addEventListener("change", () => {
                const selectedMaHx = maHxSelect.value;
                fetch(`/XeKH/GetMauXeList?maHx=${selectedMaHx}`)
                    .then(response => response.json())
                    .then(data => {
                        maMxSelect.innerHTML = '<option value="">Chọn mẫu xe</option>';
                        data.forEach(mauXe => {
                            maMxSelect.innerHTML += `<option value="${mauXe.value}">${mauXe.text}</option>`;
                        });
                        const selectedMx = maMxSelect.value;
                        maMxHidden.value = selectedMx; // Cập nhật giá trị của trường ẩn
                    });
            });
            maMxSelect.addEventListener("change", () => {
                const selectedMx = maMxSelect.value;
                maMxHidden.value = selectedMx; // Cập nhật giá trị của trường ẩn khi người dùng thay đổi dropdown
            });
        });
        document.addEventListener("DOMContentLoaded", () => {
            const sogheInput = document.getElementById("Soghe");
            sogheInput.addEventListener("keydown", (event) => {
                const value = parseInt(sogheInput.value);
                if (!/^\d$/.test(event.key) || (value === 0 && event.key === "ArrowDown")) {
                    event.preventDefault();
                }
            });
            sogheInput.addEventListener("input", () => {
                sogheInput.value = Math.max(parseInt(sogheInput.value), 0);
            });
        });
        document.getElementById('HinhInput').addEventListener('change', function () {
            previewImage(this);
        });
        function previewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#previewHinhDaiDienXe').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        function previewImages(input, previewId) {
            var previewContainer = document.getElementById(previewId);
            previewContainer.innerHTML = ''; // Xóa bỏ các hình ảnh hiện có để cập nhật mới

            if (input.files) {
                var files = input.files;
                for (var i = 0; i < files.length; i++) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        var img = document.createElement('img');
                        img.src = e.target.result;
                        img.style.maxWidth = '200px';
                        img.style.marginTop = '10px';
                        previewContainer.appendChild(img);
                    }
                    reader.readAsDataURL(files[i]);
                }
            }
        }
    </script>
}